#!/bin/sh

set -e

CONFFILES="/etc/clickhouse-server/config.xml
/etc/clickhouse-server/config-preprocessed.xml
/etc/clickhouse-server/users.xml
/etc/clickhouse-server/users-preprocessed.xml"

ch_user=clickhouse
ch_group=${ch_user}
if [ "${1}" = "purge" ]
then
        for CONFFILE in ${CONFFILES}
        do
                dpkg-statoverride --remove ${CONFFILE} || test $? -eq 2
        done

        userdel ${ch_user} || true
        groupdel ${ch_group} || true
fi

#DEBHELPER#
